refreshed existing templ and added private endpoint and activation
aws-quickstart/quickstart-mongodb-atlas pull request #27
Opened 2023-01-16 12:33 UTC by SuperMohit

*Description of changes:*
1. MongoDB has published the latest Atlas CFN resources in multiple AWS Regions. As a result, these quickstarts need to meet the schema constraints of the resources.
2. Activation resource is also added to allow for activating resources needed in the quickstart.
3. Private Endpoint Quickstart has also been added.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-01-18 21:17 UTC, vsnyc commented on templates/mongodb-atlas.private-endpoint.template.yaml
> +        deafault: AZ fo Subnet
Typo and indentation issue.
```suggestion
       default: AZ for subnet
```

2023-01-18 21:17 UTC, vsnyc commented on templates/mongodb-atlas.base-template.yaml
> +         deafault: AZ fo Subnet
Typo and indentation issue.
```suggestion
       default: AZ for subnet
```

2023-01-18 21:18 UTC, vsnyc commented on templates/mongodb-atlas.private-endpoint.template.yaml
> +          default: Private subnet CIDR
Fix indentation
```suggestion
        default: Private subnet CIDR
```

2023-01-18 21:19 UTC, vsnyc commented on templates/mongodb-atlas.private-endpoint.template.yaml
> +Description: MongoDB Atlas AWS CloudFormation Quickstart with VPC Peering. (qs-1rkorhefe)
Can't reuse template IDs. Replace with `qs-1tq8f0hrt`
```suggestion
Description: MongoDB Atlas AWS CloudFormation Quickstart with VPC Peering. (qs-1tq8f0hrt)
```

2023-01-18 21:21 UTC, vsnyc commented on templates/activate-mongodb-atlas-resources.yaml
> +Description: MongoDB Resource activation. (qs-1rkorhec7)
Can't reuse template IDs. Replace with `qs-1tq8f0hon`.
```suggestion
Description: MongoDB Resource activation. (qs-1tq8f0hon)
```

2023-01-18 21:22 UTC, vsnyc commented on templates/mongodb-atlas.base-template.yaml
> +Description: MongoDB Atlas AWS CloudFormation Quickstart. (qs-1rkorhec7)
Can't reuse template IDs. Replace with: `qs-1tq8f0hrl`.
```suggestion
Description: MongoDB Atlas AWS Partner Solution. (qs-1tq8f0hrl))
```

2023-01-18 21:24 UTC, vsnyc commented on templates/mongodb-atlas.base-template.yaml
> +    Default: "4.4"
Can't we default to the latest version and removed old version that customers should no longer use from the `AllowedValues` list?

2023-01-18 21:31 UTC, vsnyc commented on templates/mongodb-atlas-main.template.yaml
> +        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/activate-mongodb-atlas-resources.yaml'
We should rename the resource from `RegisterAtlasResources` to `ActivateAtlasResources` for consistency. The condition should be renamed as well.

2023-01-18 21:39 UTC, vsnyc requested changes
Added review comments inline. In addition, do the following changes:

1. Rename `activate-mongodb-atlas-resources.yaml` to `activate-mongodb-atlas-resources.template.yaml`.
2. Rename `mongodb-atlas.base-template.yaml` to `mongodb-atlas.base.template.yaml`.
3. Delete `register-mongodb-atlas-resources.yaml` - the file is no longer used.
4. Can we add a test for the private endpoint configuration?
5. Also, could you test the code with taskcat and attach a zip of the `taskcat_outputs` demonstrating a successful test run?

After that the submodule dependencies need to be updated, I can fix that.

2023-01-20 02:17 UTC, SuperMohit commented on templates/mongodb-atlas.private-endpoint.template.yaml
> +  VPCCIDR:
Yes, for creating VPC

2023-01-20 19:59 UTC, vsnyc commented
@SuperMohit - I am not seeing your changes for the resolved issues? Have you pushed them yet?

2023-01-21 05:02 UTC, SuperMohit commented
@vsnyc I have resolved most of the comments. I need to update taskcat.

2023-01-24 13:54 UTC, SuperMohit commented
https://quickstart-pi.s3.amazonaws.com/quickstart-temp/tCaT-mdb-atlas-pvt-endpoint-658e92-us-east-1-cfnlogs.txt
taskcat for pvtendpoint.

2023-01-25 15:27 UTC, vsnyc commented
Thansk @SuperMohit , do you have taskcat_output's from the other two tests as well - Atlas without PrivateLink or VPC Peering, and Atlas with VPC Peering?

2023-01-26 11:44 UTC, SuperMohit commented
> Thansk @SuperMohit , do you have taskcat_output's from the other two tests as well - Atlas without PrivateLink or VPC Peering, and Atlas with VPC Peering?

https://quickstart-pi.s3.amazonaws.com/quickstart-temp/taskcat_outputs.zip

2023-01-26 15:54 UTC, vsnyc approved these changes

2023-01-26 15:54 UTC, merged